import React from 'react'
import Head from 'next/head'

function Logo() {
  return (
    <>
    <Head>
        <title>Project | Logo Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./images.jpeg" />
    </Head>

        <div className='flex justify-center'>This one is our heaading</div>
    </>
  )
}

export default Logo;